name: Auto-Comment on New Issues
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post Comment with Creator and Date
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const creator = context.payload.issue.user.login;
            const createdAt = new Date(context.payload.issue.created_at).toISOString();
            const comment = `👤 **Created by:** @${creator}\n📅 **Date Created:** ${createdAt}`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issueNumber,
              body: comment
            });
