name: Update GitHub Project Fields

on:
  issues:
    types: [opened] # Runs when a new issue is created
  workflow_dispatch: # Allows manual trigger

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "$GH_PAT" | gh auth login --with-token

      - name: Get Issue Data
        id: issue_data
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          ISSUE_ID=$(gh issue list --state open --limit 1 --json number --jq '.[0].number')
          CREATOR=$(gh issue view "$ISSUE_ID" --json author --jq '.author.login')
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV
          echo "CREATOR=$CREATOR" >> $GITHUB_ENV

      - name: Update GitHub Project Fields
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ORGANIZATION: Ricamslv
          PROJECT_NUMBER: 3
        run: |
          if [ -n "$ISSUE_ID" ]; then
            gh project item-edit --project "$PROJECT_NUMBER" \
              --field "created_at=$(date +%Y-%m-%d)" \
              --field "creator=@$CREATOR"
          else
            echo "No open issues found. Skipping project update."
          fi
