name: Update GitHub Project Fields

on:
  issues:
    types: [opened] # Runs when a new issue is created
  workflow_dispatch: # Allows manual trigger

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "$GH_PAT" | gh auth login --with-token

      - name: Get Issue and Project Data
        id: issue_data
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ORGANIZATION: Ricamslv
          PROJECT_NUMBER: 3
        run: |
          # Get Project ID from Organization Projects
          PROJECT_ID=$(gh project list --owner "$ORGANIZATION" --format json | jq -r '.[] | select(.number == '"$PROJECT_NUMBER"') | .id')

          # Get the latest issue number
          ISSUE_ID=$(gh issue list --state open --limit 1 --json number --jq '.[0].number')

          # Get the creator's GitHub username
          CREATOR=$(gh issue view "$ISSUE_ID" --json author --jq '.author.login')

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV
          echo "CREATOR=$CREATOR" >> $GITHUB_ENV

      - name: Get Issue Item ID from Project
        id: get_item_id
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Get the issue item ID from the project
          ITEM_ID=$(gh project item-list --project-id "$PROJECT_ID" --format json | jq -r '.items[] | select(.content.number == '"$ISSUE_ID"') | .id')

          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV

      - name: Update GitHub Project Fields
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ORGANIZATION: Ricamslv
          PROJECT_NUMBER: 3
        run: |
          if [ -n "$ISSUE_ID" ]; then
            PROJECT_ID=$(gh project list --owner "$ORGANIZATION" --format json | jq -r '.[] | select(.number == '"$PROJECT_NUMBER"') | .id')
            
            gh project item-edit --project-id "$PROJECT_ID" \
              --field "created_at=$(date +%Y-%m-%d)" \
              --field "creator=@$CREATOR"
          else
            echo "No open issues found. Skipping project update."
          fi